mysql:
  build: $DB_DOCKERFILE_DIR
  ports:
    - "3306:3306"
  environment:
    MYSQL_DATABASE : myapp_development
    MYSQL_USER : myapp
    MYSQL_PASSWORD : myapp_pass
    MYSQL_ROOT_PASSWORD : _root_
webapp:
  build: $WEBAPP_DOCKERFILE_DIR
  ports:
    - "80:8080"
  links:
    - mysql:mysql
  volumes:
    - ${APP_ROOT_DIR}:/var/data
  command: /var/scripts/start_webapp.sh

